-- loader_example.lua
-- REMOVED: this file was a duplicate of the loader functionality.
-- Keeping a single canonical script at scripts/randomencounter.lua.
-- If you want this file fully deleted instead of replaced with this note,
-- tell me and I'll remove it (I can also rename/move files if you'd prefer).
